name: Image Info

on: [push, pull_request, workflow_dispatch]

jobs:
  Windows:
    name: >-
      ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: working_directory
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-2019, windows-2016 ]

    steps:
      - name: repo checkout
        uses: actions/checkout@v2

      - name: show ENV
        run:  gci env:* | sort-object name | Out-String -Stream -Width 120

      - name: show PATH
        run:  Write-Host $env:PATH.replace(";", "`n")

      - name: disk info
        run:  Get-CimInstance Win32_LogicalDisk

      - name: dir C:/
        run:  dir C:/

      - name: dir C:/hostedtoolcache/windows
        run:  dir C:/hostedtoolcache/windows

      - name: dir C:/hostedtoolcache/windows/Ruby
        run:  dir C:/hostedtoolcache/windows/Ruby

      - name: dir C:/Program Files
        run:  dir 'C:/Program Files'

      - name: dir C:/tools
        run:  dir C:/tools

      - name: dir C:/Users
        run:  dir C:/Users

      - name: dir C:/msys64/home
        run:  dir C:/msys64/home

      - name: where & version info
        run:  ./where.ps1

      - name: Ruby info
        run:  |
          # Ruby Info ps1
          ruby -W0 -e 'puts %Q(TOPDIR   #{RbConfig::TOPDIR})'
          ruby -W0 -e 'puts %Q(bindir   #{RbConfig::CONFIG[%q(bindir)]})'
          echo ''
          ruby -W0 -e 'puts %Q(Gem.path), Gem.path'

      - name: Ruby info bash
        shell: bash
        run:  |
          # Ruby Info
          ruby -W0 -e 'puts %Q(TOPDIR   #{RbConfig::TOPDIR})'
          ruby -W0 -e 'puts %Q(bindir   #{RbConfig::CONFIG[%q(bindir)]})'
          echo ''
          ruby -W0 -e 'puts %Q(Gem.path), Gem.path'

      - name: MSYS2 packages
        run:  ruby pacman_query.rb

  Ubuntu-macOS:
    name: >-
      ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-20.04, ubuntu-18.04, ubuntu-16.04, macos-11.0, macos-10.15 ]

    steps:
      - name: repo checkout
        uses: actions/checkout@v2

      - name: disk info
        run:  df -h

      - name:  show ENV
        shell: pwsh
        run:   gci env:* | sort-object name | Out-String -Stream -Width 120

      - name:  show PATH
        shell: pwsh
        run:   echo $env:PATH.replace([IO.Path]::PathSeparator, "`n")

      - name:  apt list --installed
        if:    startsWith(matrix.os, 'ubuntu')
        run:   apt list --installed

      - name:  Open fd limit
        if:    startsWith(matrix.os, 'windows') == false
        run:   echo Open fd limit $(ulimit -n)

      - name: misc version info
        run:  |
          openssl version
          gcc --version

      - name:  Ruby info
        shell: pwsh
        run:  |
          # Ruby Info
          ruby -W0 -e 'puts %Q(TOPDIR   #{RbConfig::TOPDIR})'
          ruby -W0 -e 'puts %Q(bindir   #{RbConfig::CONFIG[%q(bindir)]})'
          echo ''
          ruby -W0 -e 'puts %Q(Gem.path), Gem.path'
          echo ''
          echo 'which ruby:'
          which -a ruby
          echo ''
          echo 'which rake:'
          which -a rake
