name: MSYS2 bash shell

on: [push, pull_request]

jobs:
  Windows:
    name: >-
      ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest ]
        ruby: [ mingw ]
    steps:
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name:  MSYS2 bash test
        shell: bash.exe --noprofile --norc -e -o pipefail {0}
        run:   |
          openssl version
          tar --version
          pacman --version
          gcc --version
